[[redirects]]
  from = "/*"
  to = "/Profile.js"
 
  conditions = {Language = ["en"], Country = ["US"]]}

  [[redirects]]
  from = "Profile.js"
  to = "/Details.js"
 
  conditions = {Language = ["en"], Country = ["US"]]}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/Details"
  to = "https://indapi.kumba.io/webdev/assignment"
 
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
 [[redirects]]
  from = "/User"
  to = "https://indapi.kumba.io/webdev/assignment"
 
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}